### ISSUE TITLE
No config file to specify only armor/etc

### ISSUE THREAD

**Issue by edgedick** [brianmiller/nomovementpenalty#1]
I realize this isn't really an issue per se, more a request; would it be possible to add a config file to let people exclude things from the movespeed calculation?

Personally, I'd like to get rid of the armor penalty, but leave the weapon/tool penalty to give a reason to sheathe stuff.

Otherwise, thanks for the mod!

**Comment by brianmiller** [comment]
This shouldn't be a problem. I'll take a look tomorrow.

**Comment by brianmiller** [comment]
Completed with commit: https://github.com/brianmiller/nomovementpenalty/commit/f3a9f8eaa89679684ce4d5e3fd81a280c9a1f751
